### ISSUE TITLE
Warning: more than one paella player instance with enabled shortcut plugins

### ISSUE THREAD

**Issue by berthob98** [Opencast-Moodle/moodle-mod_opencast#23] opened 2022-09-05 16:42 UTC
When embedding **more than one** video the Paella UI is not usable and Firefox throws Warning:

`paella-core  - Warning: Warning: more than one paella player instance with enabled shortcut plugins. [paella-core.js:2:691761](webpack://MoodlePaellaPlayer/node_modules/paella-core/dist/paella-core.js)
paella-core  - Warning: Check your code to ensure that only one instance of paella player registers keyboard shortcut plugins.`

Moodle Version: 3.9.10+
Opencast Version: Opencast 10.13.0
We migrated from the LTI Plugin Stack to the new Plugin Stack
Paella Config is not changed

**Comment by MatthiasKollenbroichWWU** [comment] 2022-10-14 10:20
Unfortunately, we were not able to reproduce this issue with Firefox (or with Chrome). Are your plugins up to date?

**Comment by justusdieckmann** [comment] 2024-03-01 00:40
Hey @berthob98,

I am currently going through older issues. Since the your last activity on this issue is quite some time ago, I will close it for now. If it is still relevant to you, please do reopen the issue! In that case: How exactly are you embedding the videos?

Cheers
Justus

**Closed by justusdieckmann** 2024-03-01 00:40 UTC
